### ISSUE TITLE
Live and StoryVoiceline unable to play

### ISSUE THREAD

**Issue by RTMKXXIII** [MarshmallowAndroid/UmaMusumeExplorer#15]
Greetings! 
It seems that after a certain game update, Cygames has changed some file path, now attempting to play any Live will shows: "music data not found." I'm sure I have downloaded all the game data. I also tried using Umaviewer to play the live, but it still didn't work, It must be CY's great job.
Could you take a look at it when you have a moment? Thank you again for all your great work!
![image](https://github.com/user-attachments/assets/46b6fd80-e749-430a-9e60-eb77d38a7333)

**Comment by MarshmallowAndroid** [comment]
The file paths have not been changed, but unfortunately the game now deletes the live data and voices every time you log in (presumably to save space since the game is getting bigger). The only way to play lives right now is to launch the live with the characters you want from the game itself.

The only other way is to download the data directly from their servers. I'm not sure if I want to add this since the entire point of this application is to read local games files, but if the feature is requested enough then I will implement the ability to download and cache those files.

**Comment by RTMKXXIII** [comment]
Thank you for your reply! That makes sense now. I checked my game files, and they’re currently only 24GB, whereas they were over 30GB last time I looked. As for downloading files online, I found a webpage that can help with this. If anyone else encounters the same issue as me, you can use: https://snep.pw/uma/mixer/umapyoi-densetsu
