### ISSUE TITLE
To Ask A Few Questions

### ISSUE THREAD

**Issue by ChihyuenWang** [MarshmallowAndroid/UmaMusumeExplorer#2]
Hi there. I found this project by chance, and after trying it, I think it's a very useful program. Now I wanna report a few questions. (I’m not a native speaker of English. Please forgive me if there's any mistake in my expression.) 

1.The default size of the "Character Info" window can be a little smaller. Too much space is reserved now in the window. It's hard for me to use the buttons at the top.
![Snipaste_2022-09-16_23-24-04](https://user-images.githubusercontent.com/12523783/190676121-aaf90ca6-7e32-4ad0-99f9-3f1481d59875.png)

2.In the "Race Music Simulator", if I don't select anything here, and then click "Load", the program will raise an error.
![Snipaste_2022-09-16_23-26-04](https://user-images.githubusercontent.com/12523783/190676426-98ecf9ec-16ec-41e9-a91b-0cc76f86d5ad.png)

3.One suggestion: For convenience, it may be better to add the same control buttons as the Audio Player (Toggle Play, etc.) to the "Race Music Simulator" .

4.Do you have plans to add multi-language support for this program in the future? If so, I think I would be very willing to help you add the translation text of Simplified Chinese.

Thanks.

**Comment by MarshmallowAndroid** [comment]
Hello! Even I'm surprised you found this project because of how unknown it is, but thank you. Don't worry, your English is perfectly fine and understandable. No need to apologize, even just putting in effort is worth recognition :)

To answer your questions:

1. You are right. That window is far too tall and has too much blank space at the bottom. I will decrease the height in the next release. As for the illusion of blank space at the top, this is because the icon image itself has a lot of space. Running the project in Visual Studio and turning on the borders shows this.
![image](https://user-images.githubusercontent.com/19908167/190716134-9a2b60fa-c5b1-4ca1-bac0-90c0397d9a94.png)
I will try to implement auto-cropping the image in the future to mitigate this issue. Thanks for your feedback.

2. The race music simulator is more or less an experiment that I just left in there, evidently shown by the error raised in your screenshot. It can be fixed by a simple null check in the button event that I surprisingly didn't put in like the idiot I am.

3. I agree with adding the button controls, I will work on it in the next release.

4. I actually never expected anyone aside from myself to use this program so I never planned on multi-language support. However, that's not the case anymore apparently, so I'll work on making the project ready for localization, and your contributions will be very welcome.

I hope these answers your questions. Thank you.

**Comment by ChihyuenWang** [comment]
I'm surprised that you quickly fixed some of the questions I've just raised. Thanks for your attention and reply.
I will continue to follow this project and look forward to your further progress in development.
